; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:WS-ESP32-S3-LCD-1-85C]
platform        = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board           = WS-ESP32-S3-LCD-1-85C         
framework       = arduino


board_upload.flash_size    = 16MB
board_upload.maximum_size  = 16777216
board_build.partitions     = default_16MB.csv  ;partitions.csv


build_flags =
  -w
  -DBOARD_HAS_PSRAM                        
  ; -mfix-esp32-psram-cache-issue  ; Only needed for original ESP32, not ESP32-S3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
              
board_build.psram_type = opi

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

monitor_speed = 115200